services:
    odoo:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8069:8069"
        volumes:
            - odoo-data:/var/lib/odoo
            - ./addons:/mnt/extra-addons
            - ./odoo.conf:/etc/odoo/odoo.conf
        environment:
            - HOST=db
            - USER=odoo
            - PASSWORD=${ODOO_DB_PASSWORD:-odoo}
    db:
        restart: unless-stopped
        image: postgres:14
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U odoo"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    odoo-data:
    db-data: